version: '3.8'

services:
  web:
    image: jorgeiras/buscainstrumentos_back:latest  
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DROPLET_IP=${DROPLET_IP}
    command: gunicorn --workers=3 --timeout=120 --bind 0.0.0.0:8000 buscainstrumentos_back.wsgi:application
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/:ro
      - static_volume:/home/djangouser/buscainstrumentos_back
      - /home/djangouser/certbot/www/:/var/www/certbot/:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /home/djangouser/certbot/www/:/var/www/certbot/:rw
      - /home/djangouser/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume:
  media_volume:
  certbot_certs:
  certbot_challenges:

