# Generated by Django 4.1.7 on 2024-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=1000, unique=True)),
                ('website', models.CharField(default='null', max_length=500)),
                ('image', models.CharField(default='null', max_length=1000)),
                ('location', models.CharField(default='null', max_length=500)),
                ('category', models.CharField(default='null', max_length=200)),
                ('expiration', models.DateField()),
                ('publish', models.DateField()),
            ],
        ),
    ]
