# Generated by Django 4.1.7 on 2024-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscainstrumentos_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='expiration',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='location',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='publish',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='website',
            field=models.CharField(max_length=500),
        ),
    ]
