# Generated by Django 4.1.7 on 2024-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscainstrumentos_API', '0002_alter_instrument_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
