# Generated by Django 4.1.3 on 2022-12-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=1000)),
                ('WebSite', models.CharField(max_length=100)),
            ],
        ),
    ]
